api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
        multipart:
            mime_types: ['multipart/form-data']
    eager_loading:
        force_eager: false